### ISSUE TITLE
0.7.2. Stack-less node shutdown happens out of the blue intermittently

### ISSUE THREAD

**Issue by hodlonaut** [input-output-hk/jormungandr#1201]
jcli --full-version
jcli 0.7.2 (master-fcf26869, release, macos [x86_64]) - [rustc 1.39.0 (4560ea788 2019-11-04)]

jormungandr --full-version
jormungandr 0.7.2 (master-fcf26869, release, macos [x86_64]) - [rustc 1.39.0 (4560ea788 2019-11-04)]

Steps to reproduce:

Start the node in leader/block-producing mode, let it run for a while

Debug level log just preceding the unexpected shutdown:
----------------------------------------------------------

Nov 26 21:47:25.103 INFO switching to new candidate branch, task: block
Nov 26 21:47:25.103 DEBG propagating block, hash: 43da1df000a9c57ca19879d2c27b82a0633911b4d5938fe31c370bfd8f5bef0c, task: network
Nov 26 21:47:28.883 DEBG sending gossip, node_id: 0bb213eb0623283e9c55ddce81a2e5de6e19c50702acd1ab, task: network
Nov 26 21:47:38.884 DEBG sending gossip, node_id: 0bb213eb0623283e9c55ddce81a2e5de6e19c50702acd1ab, task: network
Nov 26 21:47:48.881 DEBG sending gossip, node_id: 0bb213eb0623283e9c55ddce81a2e5de6e19c50702acd1ab, task: network
Nov 26 21:47:49.334 DEBG propagating fragment, task: network
Nov 26 21:47:58.882 DEBG sending gossip, node_id: 0bb213eb0623283e9c55ddce81a2e5de6e19c50702acd1ab, task: network
Nov 26 21:48:08.882 DEBG sending gossip, node_id: 0bb213eb0623283e9c55ddce81a2e5de6e19c50702acd1ab, task: network
Nov 26 21:48:14.001 INFO Leader event started, event_remaining_time: 4s 998ms 780us, event_end: 2019-11-26T10:48:19+00:00, event_start: 2019-11-26T10:48:14+00:00, event_date: 652.92, leader_id: 1, task: leadership
Nov 26 21:48:14.002 DEBG awaiting, leader_id: 1, event_date: 652.114, task: leadership
Nov 26 21:48:14.002 DEBG processing block from leader event, date: 652.92, parent: 43da1df000a9c57ca19879d2c27b82a0633911b4d5938fe31c370bfd8f5bef0c, hash: c192e7242da185523620317296362fd321facafe09380ed6997ceeec66896d30, task: block
Nov 26 21:48:14.019 ERRO Cannot process block event, reason: cannot process leadership block, task: block
Nov 26 21:48:14.020 INFO Shutting down node

Attaching a log file from a separate shutdown of similar nature earlier

[debugLogShutdownNode_0_7_2.txt](https://github.com/input-output-hk/jormungandr/files/3891442/debugLogShutdownNode_0_7_2.txt)

**Comment by dorin100** [comment]
I also experienced this multiple times when using `0.7.2` with the QA testnet. Based on @mzabaluev 's investigation it might be related to nodes from the testnet crashing/panicking because of https://github.com/input-output-hk/jormungandr/issues/881

**Comment by bjarnekvae** [comment]
This happened to me as well, running v0.7.4. Does not seem to be a panic as I did not get any rust backtrace output.

**Comment by mzabaluev** [comment]
One likely cause was fixed in #1218. Please re-check with version 0.7.5.

**Comment by bjarnekvae** [comment]
Still happens on 0.7.5:

[shutdown2.zip](https://github.com/input-output-hk/jormungandr/files/3900384/shutdown2.zip)

**Comment by hodlonaut** [comment]
Latest git master build (0.8 rc1) also exhibits this behaviour shortly after starting on a network with some 0.7.5 and 0.7.1/0.7 nodes:

Nov 28 20:58:44.961 INFO switching to new candidate branch, task: block
Nov 28 20:58:44.962 DEBG propagating block, hash: 28b15b2890f81c9b4bb73ecf7762ad4e5b45bfdfe80136b380319aa0e2f7ef43, task: network
Nov 28 20:58:44.962 DEBG propagation to peer failed, unsubscribing peer, reason: not subscribed, node_id: 57cc58baf17fc08d0c451700a2c1d2a9f7c598f47a9da20a, task: network
Nov 28 20:58:44.962 DEBG 1 of the peers selected for propagation have not been reached, will try to connect, task: network
Nov 28 20:58:44.962 INFO connecting to peer, node_id: 57cc58baf17fc08d0c451700a2c1d2a9f7c598f47a9da20a, peer_addr: 84.114.140.53:7997, task: network
Nov 28 20:58:44.962 DEBG connection to peer has been canceled, node_id: 57cc58baf17fc08d0c451700a2c1d2a9f7c598f47a9da20a, peer_addr: 84.114.140.53:7997, task: network
Nov 28 20:58:45.286 DEBG peer requests missing part of the chain, to: Hash(Blake2b256(0x28b15b2890f81c9b4bb73ecf7762ad4e5b45bfdfe80136b380319aa0e2f7ef43)), checkpoints: [Hash(Blake2b256(0x2baa97aaa2217c1e5aaeca4c3c0abbdb106fb6c76f31b52b0148148d98c31955)), Hash(Blake2b256(0xdbf75fcb1d929adf89dcbed7eae41cb3f676357c10f33fb9e128729724e4e1da)), Hash(Blake2b256(0xbeaab9c2c5a5a0d6cec1a1db6ea1382497848bff656710fc789e5184c1ef32ba)), Hash(Blake2b256(0x3009e3de217de83f7bcd5ca43b6c6b01e988560ef694928d21af01c4a74ff192)), Hash(Blake2b256(0x26432ca4407d28ffc0d6c0a0d3728d9bc6e5182e7439dec1fd3dc116045055ea)), Hash(Blake2b256(0xc0e348b7d0893e5fbba94891fa0d6a39ef4719a3756849fb9e0deb8147ddad1d)), Hash(Blake2b256(0xd2716776d36128d89c9a88514937e5457543705429b1005498d0e81be82894e0)), Hash(Blake2b256(0xb77c2b9dfc72d3e4ea4a7f59e425fec3ed33ff7643e53cbf3f20dafc51384dd2)), Hash(Blake2b256(0x80ea76e830e2409271e09cfed1889fb3e859aef25be78ec2d739fdd432fffe3c)), Hash(Blake2b256(0xcf9a9e8a26b5049734d554b19d713474b80c212af1086afdfcb2127ca7331fa6)), Hash(Blake2b256(0xca4d57e916073c002763c6e633fd3291c16664445e84f31647b4d23caf658752)), Hash(Blake2b256(0xbef9de0aab7ed44c134ce9e48d497b357b56fa0577ec2722e710052d698601d7)), Hash(Blake2b256(0x3dc55c9defef74192d8eb90c7ce21ec230f21d09be72d68d8c4dd754d93c6a30)), Hash(Blake2b256(0xeba1112e255041e8d066527835c8b8448d05eb026dc0ebf0a145a87341be9377)), Hash(Blake2b256(0x21dc8616ec9c913aa5f94261b87f7b208011f2e6b1ceca8be22126db3ff13532)), Hash(Blake2b256(0x4597088a766660edf1730f04ae8a40dfce98efb3a7d855e5884b4db1abecc9d0)), Hash(Blake2b256(0x2a6e165647fe624a624786bd29637d0fe60b0c450803d0163f204ca74c024479)), Hash(Blake2b256(0x2d044f2f77a81e33c40c609cfebf54d65417b9fd354ea0ac7789a76eaac46490)), Hash(Blake2b256(0xe356275aa3d751b35fe22513d9fa068d3adcb82caf16613712795424f0a386f1))], node_id: ada4cafebabecafebabecafebabecafebabecafebabe4ada, peer_addr: 185.161.193.61:9030, task: network
Nov 28 20:58:45.991 DEBG peer requests 32 blocks, node_id: ada4cafebabecafebabecafebabecafebabecafebabe4ada, peer_addr: 185.161.193.61:9030, task: network
Nov 28 20:58:46.027 DEBG finished pushing headers, node_id: ada4cafebabecafebabecafebabecafebabecafebabe4ada, peer_addr: 185.161.193.61:9030, task: network
Nov 28 20:58:46.027 INFO Shutting down node

**Comment by mzabaluev** [comment]
With #1230, more information is logged about the cause of the shutdown, message "service finished with ...".

**Comment by disassembler** [comment]
Issue still occurs on 0.8.0-rc3. Here's one second of the logs in verbose mode showing all the line numbers, code files and modules where it's occurring.

Note that we had all the nodes stable on rc2, and as soon as we deployed rc3, all the trusted peers started experiencing this except the one I rotated the IP of last night (so no 3rd party nodes can connect to it anymore.

```
-- Logs begin at Mon 2019-11-25 22:33:31 UTC, end at Sun 2019-12-01 12:19:59 UTC. --
Sun 2019-12-01 11:47:08.257938 UTC [s=88b500d1b0454e0997be9fd88e5439de;i=c30129;b=9b747d2c918947f89f6e0ecabb670088;m=70ef8785c0;t=598a305d176e9;x=ed0b66620ec05830]
    PRIORITY=5
    CODE_FUNCTION=
    TASK=network
    SYSLOG_IDENTIFIER=jormungandr
    _TRANSPORT=journal
    _UID=10015
    _GID=10015
    _COMM=jormungandr
    _CAP_EFFECTIVE=0
    _SYSTEMD_CGROUP=/system.slice/jormungandr.service
    _SYSTEMD_UNIT=jormungandr.service
    _SYSTEMD_SLICE=system.slice
    _BOOT_ID=9b747d2c918947f89f6e0ecabb670088
    _MACHINE_ID=ec2ab651a12df8fa10696b87f7f042fb
    _HOSTNAME=relay-ap-northeast-1-2
    MESSAGE=incoming connection on 172.31.42.141:3000
    CODE_FILE=jormungandr/src/network/grpc/server.rs
    CODE_LINE=49
    CODE_MODULE=jormungandr::network::grpc::server
    _EXE=/nix/store/55q9d5cmh5h3ifrwn62kj96smpab2n7p-jormungandr-0.8.0-rc3/bin/jormungandr
    _CMDLINE=/nix/store/55q9d5cmh5h3ifrwn62kj96smpab2n7p-jormungandr-0.8.0-rc3/bin/jormungandr --genesis-block /nix/store/dlqhg5shym40d8arl5xgbw2bzfryvh23-block-0.bin --config /nix/store/cbhzl97m3a5k4d24lhqvq51n70wdhns6-config.yaml
    _PID=21475
    _SYSTEMD_INVOCATION_ID=a48e0dbf27004794829ecf0838875174
    PEER_ADDR=2.56.214.85:33006
    _SOURCE_REALTIME_TIMESTAMP=1575200828257938
Sun 2019-12-01 11:47:08.277819 UTC [s=88b500d1b0454e0997be9fd88e5439de;i=c3012a;b=9b747d2c918947f89f6e0ecabb670088;m=70ef87d324;t=598a305d1c44d;x=20e57b354415b2ec]
    CODE_FUNCTION=
    SYSLOG_IDENTIFIER=jormungandr
    _TRANSPORT=journal
    _UID=10015
    _GID=10015
    _COMM=jormungandr
    _CAP_EFFECTIVE=0
    _SYSTEMD_CGROUP=/system.slice/jormungandr.service
    _SYSTEMD_UNIT=jormungandr.service
    _SYSTEMD_SLICE=system.slice
    _BOOT_ID=9b747d2c918947f89f6e0ecabb670088
    _MACHINE_ID=ec2ab651a12df8fa10696b87f7f042fb
    _HOSTNAME=relay-ap-northeast-1-2
    PRIORITY=6
    MESSAGE=request processed
    CODE_FILE=jormungandr/src/intercom.rs
    CODE_LINE=191
    CODE_MODULE=jormungandr::intercom
    TASK=rest
    _EXE=/nix/store/55q9d5cmh5h3ifrwn62kj96smpab2n7p-jormungandr-0.8.0-rc3/bin/jormungandr
    _CMDLINE=/nix/store/55q9d5cmh5h3ifrwn62kj96smpab2n7p-jormungandr-0.8.0-rc3/bin/jormungandr --genesis-block /nix/store/dlqhg5shym40d8arl5xgbw2bzfryvh23-block-0.bin --config /nix/store/cbhzl97m3a5k4d24lhqvq51n70wdhns6-config.yaml
    _PID=21475
    _SYSTEMD_INVOCATION_ID=a48e0dbf27004794829ecf0838875174
    _SOURCE_REALTIME_TIMESTAMP=1575200828277819
Sun 2019-12-01 11:47:08.467785 UTC [s=88b500d1b0454e0997be9fd88e5439de;i=c3012b;b=9b747d2c918947f89f6e0ecabb670088;m=70ef8ab96c;t=598a305d4aa95;x=ee88a36d9304dcf3]
    PRIORITY=5
    CODE_FUNCTION=
    TASK=network
    SYSLOG_IDENTIFIER=jormungandr
    _TRANSPORT=journal
    _UID=10015
    _GID=10015
    _COMM=jormungandr
    _CAP_EFFECTIVE=0
    _SYSTEMD_CGROUP=/system.slice/jormungandr.service
    _SYSTEMD_UNIT=jormungandr.service
    _SYSTEMD_SLICE=system.slice
    _BOOT_ID=9b747d2c918947f89f6e0ecabb670088
    _MACHINE_ID=ec2ab651a12df8fa10696b87f7f042fb
    _HOSTNAME=relay-ap-northeast-1-2
    CODE_FILE=jormungandr/src/network/grpc/server.rs
    CODE_MODULE=jormungandr::network::grpc::server
    MESSAGE=incoming HTTP/2 connection error
    CODE_LINE=63
    _EXE=/nix/store/55q9d5cmh5h3ifrwn62kj96smpab2n7p-jormungandr-0.8.0-rc3/bin/jormungandr
    _CMDLINE=/nix/store/55q9d5cmh5h3ifrwn62kj96smpab2n7p-jormungandr-0.8.0-rc3/bin/jormungandr --genesis-block /nix/store/dlqhg5shym40d8arl5xgbw2bzfryvh23-block-0.bin --config /nix/store/cbhzl97m3a5k4d24lhqvq51n70wdhns6-config.yaml
    REASON=connection error: Connection reset by peer (os error 104)
    _PID=21475
    _SYSTEMD_INVOCATION_ID=a48e0dbf27004794829ecf0838875174
    PEER_ADDR=2.56.214.85:33006
    _SOURCE_REALTIME_TIMESTAMP=1575200828467785
Sun 2019-12-01 11:47:08.468183 UTC [s=88b500d1b0454e0997be9fd88e5439de;i=c3012c;b=9b747d2c918947f89f6e0ecabb670088;m=70ef8abb42;t=598a305d4ac6b;x=f5f67bb3a86033b2]
    PRIORITY=5
    CODE_FUNCTION=
    SYSLOG_IDENTIFIER=jormungandr
    _TRANSPORT=journal
    _UID=10015
    _GID=10015
    _COMM=jormungandr
    _CAP_EFFECTIVE=0
    _SYSTEMD_CGROUP=/system.slice/jormungandr.service
    _SYSTEMD_UNIT=jormungandr.service
    _SYSTEMD_SLICE=system.slice
    _BOOT_ID=9b747d2c918947f89f6e0ecabb670088
    _MACHINE_ID=ec2ab651a12df8fa10696b87f7f042fb
    _HOSTNAME=relay-ap-northeast-1-2
    _EXE=/nix/store/55q9d5cmh5h3ifrwn62kj96smpab2n7p-jormungandr-0.8.0-rc3/bin/jormungandr
    _CMDLINE=/nix/store/55q9d5cmh5h3ifrwn62kj96smpab2n7p-jormungandr-0.8.0-rc3/bin/jormungandr --genesis-block /nix/store/dlqhg5shym40d8arl5xgbw2bzfryvh23-block-0.bin --config /nix/store/cbhzl97m3a5k4d24lhqvq51n70wdhns6-config.yaml
    MESSAGE=service finished with error
    CODE_FILE=jormungandr/src/utils/task.rs
    CODE_LINE=124
    CODE_MODULE=jormungandr::utils::task
    TASK=client-query
    _PID=21475
    _SYSTEMD_INVOCATION_ID=a48e0dbf27004794829ecf0838875174
    _SOURCE_REALTIME_TIMESTAMP=1575200828468183
Sun 2019-12-01 11:47:08.468196 UTC [s=88b500d1b0454e0997be9fd88e5439de;i=c3012d;b=9b747d2c918947f89f6e0ecabb670088;m=70ef8abbaf;t=598a305d4acd9;x=a5dbca029a672003]
    PRIORITY=5
    CODE_FUNCTION=
    SYSLOG_IDENTIFIER=jormungandr
    _TRANSPORT=journal
    _UID=10015
    _GID=10015
    _COMM=jormungandr
    _CAP_EFFECTIVE=0
    _SYSTEMD_CGROUP=/system.slice/jormungandr.service
    _SYSTEMD_UNIT=jormungandr.service
    _SYSTEMD_SLICE=system.slice
    _BOOT_ID=9b747d2c918947f89f6e0ecabb670088
    _MACHINE_ID=ec2ab651a12df8fa10696b87f7f042fb
    _HOSTNAME=relay-ap-northeast-1-2
    CODE_FILE=jormungandr/src/main.rs
    CODE_MODULE=jormungandr
    _EXE=/nix/store/55q9d5cmh5h3ifrwn62kj96smpab2n7p-jormungandr-0.8.0-rc3/bin/jormungandr
    _CMDLINE=/nix/store/55q9d5cmh5h3ifrwn62kj96smpab2n7p-jormungandr-0.8.0-rc3/bin/jormungandr --genesis-block /nix/store/dlqhg5shym40d8arl5xgbw2bzfryvh23-block-0.bin --config /nix/store/cbhzl97m3a5k4d24lhqvq51n70wdhns6-config.yaml
    MESSAGE=Shutting down node
    CODE_LINE=320
    _PID=21475
    _SYSTEMD_INVOCATION_ID=a48e0dbf27004794829ecf0838875174
    _SOURCE_REALTIME_TIMESTAMP=1575200828468196
Sun 2019-12-01 11:47:08.475448 UTC [s=9f7f37ae9a514254b88d1915cf7c59df;i=c3012f;b=9b747d2c918947f89f6e0ecabb670088;m=70ef8ad70f;t=598a305d4c838;x=1092935156c8c95c]
    _BOOT_ID=9b747d2c918947f89f6e0ecabb670088
    _MACHINE_ID=ec2ab651a12df8fa10696b87f7f042fb
    _HOSTNAME=relay-ap-northeast-1-2
    _TRANSPORT=kernel
    PRIORITY=5
    SYSLOG_FACILITY=0
    SYSLOG_IDENTIFIER=kernel
    _SOURCE_MONOTONIC_TIMESTAMP=485071290703
    MESSAGE=audit: type=1131 audit(1575200828.471:57): pid=1 uid=0 auid=4294967295 ses=4294967295 subj==unconfined msg='unit=jormungandr comm="systemd" exe="/nix/store/h6c0sb2fn70h4n33c7d3znr5bzakrzn6-systemd-243/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Sun 2019-12-01 11:47:08.471870 UTC [s=9f7f37ae9a514254b88d1915cf7c59df;i=c30130;b=9b747d2c918947f89f6e0ecabb670088;m=70ef8ad757;t=598a305d4c880;x=c3d910723aeb928b]
    PRIORITY=6
    _UID=0
    _GID=0
    _CAP_EFFECTIVE=3fffffffff
    _BOOT_ID=9b747d2c918947f89f6e0ecabb670088
    _MACHINE_ID=ec2ab651a12df8fa10696b87f7f042fb
    _HOSTNAME=relay-ap-northeast-1-2
    SYSLOG_FACILITY=3
    SYSLOG_IDENTIFIER=systemd
    _TRANSPORT=journal
    _PID=1
    _COMM=systemd
    _EXE=/nix/store/h6c0sb2fn70h4n33c7d3znr5bzakrzn6-systemd-243/lib/systemd/systemd
    _CMDLINE=systemd
    _SYSTEMD_CGROUP=/init.scope
    _SYSTEMD_UNIT=init.scope
    _SYSTEMD_SLICE=-.slice
    UNIT=jormungandr.service
    CODE_FILE=src/core/unit.c
    CODE_LINE=5747
    CODE_FUNC=unit_log_success
    MESSAGE_ID=7ad2d189f7e94e70a38c781354912448
    MESSAGE=jormungandr.service: Succeeded.
    INVOCATION_ID=a48e0dbf27004794829ecf0838875174
    _SOURCE_REALTIME_TIMESTAMP=1575200828471870
Sun 2019-12-01 11:47:08.472661 UTC [s=9f7f37ae9a514254b88d1915cf7c59df;i=c30131;b=9b747d2c918947f89f6e0ecabb670088;m=70ef8ad930;t=598a305d4ca59;x=5a44f45bd34fd03c]
    PRIORITY=6
    _UID=0
    _GID=0
    _CAP_EFFECTIVE=3fffffffff
    _BOOT_ID=9b747d2c918947f89f6e0ecabb670088
    _MACHINE_ID=ec2ab651a12df8fa10696b87f7f042fb
    _HOSTNAME=relay-ap-northeast-1-2
    SYSLOG_FACILITY=3
    SYSLOG_IDENTIFIER=systemd
    _TRANSPORT=journal
    _PID=1
    _COMM=systemd
    _EXE=/nix/store/h6c0sb2fn70h4n33c7d3znr5bzakrzn6-systemd-243/lib/systemd/systemd
    _CMDLINE=systemd
    _SYSTEMD_CGROUP=/init.scope
    _SYSTEMD_UNIT=init.scope
    _SYSTEMD_SLICE=-.slice
    UNIT=jormungandr.service
    CODE_FILE=src/core/unit.c
    CODE_LINE=2365
    CODE_FUNC=unit_log_resources
    MESSAGE_ID=ae8f7b866b0347b9af31fe1c80b127c0
    INVOCATION_ID=a48e0dbf27004794829ecf0838875174
    CPU_USAGE_NSEC=893152317
    IP_METRIC_INGRESS_BYTES=1384614
    IP_METRIC_INGRESS_PACKETS=8870
    IP_METRIC_EGRESS_BYTES=2179406
    IP_METRIC_EGRESS_PACKETS=7116
    MESSAGE=jormungandr.service: Consumed 893ms CPU time, received 1.3M IP traffic, sent 2.0M IP traffic.
    _SOURCE_REALTIME_TIMESTAMP=1575200828472661
Sun 2019-12-01 11:47:08.488531 UTC [s=9f7f37ae9a514254b88d1915cf7c59df;i=c30132;b=9b747d2c918947f89f6e0ecabb670088;m=70ef8b0a2a;t=598a305d4fb53;x=828777e85cd3238e]
    PRIORITY=6
    _SYSTEMD_SLICE=system.slice
    _BOOT_ID=9b747d2c918947f89f6e0ecabb670088
    _MACHINE_ID=ec2ab651a12df8fa10696b87f7f042fb
    _HOSTNAME=relay-ap-northeast-1-2
    SYSLOG_FACILITY=3
    _TRANSPORT=stdout
    SYSLOG_IDENTIFIER=prkh89ka43hqyavyjflinq541z93f3wd-jormungandr-monitor
    MESSAGE=failed to make a REST request
    _UID=63640
    _GID=63640
    _COMM=python
    _EXE=/nix/store/8lhmyjarm73453f2mdz0xli9w8sy0wvh-python3-3.7.4/bin/python3.7
    _CMDLINE=/nix/store/8lhmyjarm73453f2mdz0xli9w8sy0wvh-python3-3.7.4/bin/python /nix/store/prkh89ka43hqyavyjflinq541z93f3wd-jormungandr-monitor
    _CAP_EFFECTIVE=0
    _SYSTEMD_CGROUP=/system.slice/jormungandr-monitor.service
    _SYSTEMD_UNIT=jormungandr-monitor.service
    _STREAM_ID=bb25a331cf34464bb6ab243a693bdc6d
    _PID=7303
    _SYSTEMD_INVOCATION_ID=22d4ea917cf04697933528da850afbd1
Sun 2019-12-01 11:47:08.488531 UTC [s=9f7f37ae9a514254b88d1915cf7c59df;i=c30133;b=9b747d2c918947f89f6e0ecabb670088;m=70ef8b0a2a;t=598a305d4fb53;x=d99661b602440931]
    PRIORITY=6
    _SYSTEMD_SLICE=system.slice
    _BOOT_ID=9b747d2c918947f89f6e0ecabb670088
    _MACHINE_ID=ec2ab651a12df8fa10696b87f7f042fb
    _HOSTNAME=relay-ap-northeast-1-2
    SYSLOG_FACILITY=3
    _TRANSPORT=stdout
    SYSLOG_IDENTIFIER=prkh89ka43hqyavyjflinq541z93f3wd-jormungandr-monitor
    _UID=63640
    _GID=63640
    _COMM=python
    _EXE=/nix/store/8lhmyjarm73453f2mdz0xli9w8sy0wvh-python3-3.7.4/bin/python3.7
    _CMDLINE=/nix/store/8lhmyjarm73453f2mdz0xli9w8sy0wvh-python3-3.7.4/bin/python /nix/store/prkh89ka43hqyavyjflinq541z93f3wd-jormungandr-monitor
    _CAP_EFFECTIVE=0
    _SYSTEMD_CGROUP=/system.slice/jormungandr-monitor.service
    _SYSTEMD_UNIT=jormungandr-monitor.service
    MESSAGE=  |-> could not connect with node
    _STREAM_ID=bb25a331cf34464bb6ab243a693bdc6d
    _PID=7303
    _SYSTEMD_INVOCATION_ID=22d4ea917cf04697933528da850afbd1
Sun 2019-12-01 11:47:08.488531 UTC [s=9f7f37ae9a514254b88d1915cf7c59df;i=c30134;b=9b747d2c918947f89f6e0ecabb670088;m=70ef8b0a2a;t=598a305d4fb53;x=a86e482d57d76b74]
    PRIORITY=6
    _SYSTEMD_SLICE=system.slice
    _BOOT_ID=9b747d2c918947f89f6e0ecabb670088
    _MACHINE_ID=ec2ab651a12df8fa10696b87f7f042fb
    _HOSTNAME=relay-ap-northeast-1-2
    SYSLOG_FACILITY=3
    _TRANSPORT=stdout
    SYSLOG_IDENTIFIER=prkh89ka43hqyavyjflinq541z93f3wd-jormungandr-monitor
    _UID=63640
    _GID=63640
    _COMM=python
    _EXE=/nix/store/8lhmyjarm73453f2mdz0xli9w8sy0wvh-python3-3.7.4/bin/python3.7
    _CMDLINE=/nix/store/8lhmyjarm73453f2mdz0xli9w8sy0wvh-python3-3.7.4/bin/python /nix/store/prkh89ka43hqyavyjflinq541z93f3wd-jormungandr-monitor
    _CAP_EFFECTIVE=0
    _SYSTEMD_CGROUP=/system.slice/jormungandr-monitor.service
    _SYSTEMD_UNIT=jormungandr-monitor.service
    _STREAM_ID=bb25a331cf34464bb6ab243a693bdc6d
    _PID=7303
    _SYSTEMD_INVOCATION_ID=22d4ea917cf04697933528da850afbd1
    MESSAGE=  |-> http://172.31.42.141:3001/api/v0/account/3b35290fb14c0ac9ce7cde40204926e13b1c27a1fd3756c698118324bf0514d7: error trying to connect: Connection refused (os error 111)
Sun 2019-12-01 11:47:08.489288 UTC [s=9f7f37ae9a514254b88d1915cf7c59df;i=c30135;b=9b747d2c918947f89f6e0ecabb670088;m=70ef8b0d1e;t=598a305d4fe48;x=787f1da2c3133a13]
    PRIORITY=6
    _SYSTEMD_SLICE=system.slice
    _BOOT_ID=9b747d2c918947f89f6e0ecabb670088
    _MACHINE_ID=ec2ab651a12df8fa10696b87f7f042fb
    _HOSTNAME=relay-ap-northeast-1-2
    SYSLOG_FACILITY=3
    _TRANSPORT=stdout
    SYSLOG_IDENTIFIER=prkh89ka43hqyavyjflinq541z93f3wd-jormungandr-monitor
    _UID=63640
    _GID=63640
    _COMM=python
    _EXE=/nix/store/8lhmyjarm73453f2mdz0xli9w8sy0wvh-python3-3.7.4/bin/python3.7
    _CMDLINE=/nix/store/8lhmyjarm73453f2mdz0xli9w8sy0wvh-python3-3.7.4/bin/python /nix/store/prkh89ka43hqyavyjflinq541z93f3wd-jormungandr-monitor
    _CAP_EFFECTIVE=0
    _SYSTEMD_CGROUP=/system.slice/jormungandr-monitor.service
    _SYSTEMD_UNIT=jormungandr-monitor.service
    MESSAGE=  |-> Connection refused (os error 111)
    _STREAM_ID=bb25a331cf34464bb6ab243a693bdc6d
    _PID=7303
    _SYSTEMD_INVOCATION_ID=22d4ea917cf04697933528da850afbd1
Sun 2019-12-01 11:47:08.760421 UTC [s=9f7f37ae9a514254b88d1915cf7c59df;i=c30136;b=9b747d2c918947f89f6e0ecabb670088;m=70ef8f305d;t=598a305d92186;x=d8ee1b0ebc282e47]
    PRIORITY=6
    _UID=0
    _GID=0
    _CAP_EFFECTIVE=3fffffffff
    _BOOT_ID=9b747d2c918947f89f6e0ecabb670088
    _MACHINE_ID=ec2ab651a12df8fa10696b87f7f042fb
    _HOSTNAME=relay-ap-northeast-1-2
    SYSLOG_FACILITY=3
    SYSLOG_IDENTIFIER=systemd
    _TRANSPORT=journal
    _PID=1
    _COMM=systemd
    _EXE=/nix/store/h6c0sb2fn70h4n33c7d3znr5bzakrzn6-systemd-243/lib/systemd/systemd
    _CMDLINE=systemd
    _SYSTEMD_CGROUP=/init.scope
    _SYSTEMD_UNIT=init.scope
    _SYSTEMD_SLICE=-.slice
    UNIT=jormungandr.service
    CODE_FILE=src/core/service.c
    CODE_LINE=3754
    CODE_FUNC=service_dispatch_timer
    MESSAGE=jormungandr.service: Service RestartSec=100ms expired, scheduling restart.
    INVOCATION_ID=a48e0dbf27004794829ecf0838875174
    _SOURCE_REALTIME_TIMESTAMP=1575200828760421
Sun 2019-12-01 11:47:08.760622 UTC [s=9f7f37ae9a514254b88d1915cf7c59df;i=c30137;b=9b747d2c918947f89f6e0ecabb670088;m=70ef8f311e;t=598a305d92247;x=8dbeac2c21e30741]
    PRIORITY=6
    _UID=0
    _GID=0
    _CAP_EFFECTIVE=3fffffffff
    _BOOT_ID=9b747d2c918947f89f6e0ecabb670088
    _MACHINE_ID=ec2ab651a12df8fa10696b87f7f042fb
    _HOSTNAME=relay-ap-northeast-1-2
    SYSLOG_FACILITY=3
    SYSLOG_IDENTIFIER=systemd
    _TRANSPORT=journal
    _PID=1
    _COMM=systemd
    _EXE=/nix/store/h6c0sb2fn70h4n33c7d3znr5bzakrzn6-systemd-243/lib/systemd/systemd
    _CMDLINE=systemd
    _SYSTEMD_CGROUP=/init.scope
    _SYSTEMD_UNIT=init.scope
    _SYSTEMD_SLICE=-.slice
    UNIT=jormungandr.service
    CODE_FILE=src/core/service.c
    CODE_LINE=2279
    CODE_FUNC=service_enter_restart
    MESSAGE_ID=5eb03494b6584870a536b337290809b3
    INVOCATION_ID=a48e0dbf27004794829ecf0838875174
    MESSAGE=jormungandr.service: Scheduled restart job, restart counter is at 5.
    N_RESTARTS=5
    _SOURCE_REALTIME_TIMESTAMP=1575200828760622
Sun 2019-12-01 11:47:08.760922 UTC [s=9f7f37ae9a514254b88d1915cf7c59df;i=c3013a;b=9b747d2c918947f89f6e0ecabb670088;m=70ef8f34b8;t=598a305d925e2;x=a7a4a4827b6945f9]
    PRIORITY=6
    _UID=0
    _GID=0
    _CAP_EFFECTIVE=3fffffffff
    _BOOT_ID=9b747d2c918947f89f6e0ecabb670088
    _MACHINE_ID=ec2ab651a12df8fa10696b87f7f042fb
    _HOSTNAME=relay-ap-northeast-1-2
    SYSLOG_FACILITY=3
    CODE_FILE=src/core/job.c
    SYSLOG_IDENTIFIER=systemd
    _TRANSPORT=journal
    _PID=1
    _COMM=systemd
    _EXE=/nix/store/h6c0sb2fn70h4n33c7d3znr5bzakrzn6-systemd-243/lib/systemd/systemd
    _CMDLINE=systemd
    _SYSTEMD_CGROUP=/init.scope
    _SYSTEMD_UNIT=init.scope
    _SYSTEMD_SLICE=-.slice
    CODE_LINE=931
    CODE_FUNC=job_log_done_status_message
    JOB_RESULT=done
    UNIT=jormungandr.service
    MESSAGE=Stopped Jormungandr node service.
    MESSAGE_ID=9d1aaa27d60140bd96365438aad20286
    JOB_TYPE=restart
    INVOCATION_ID=a48e0dbf27004794829ecf0838875174
    JOB_ID=53726
    _SOURCE_REALTIME_TIMESTAMP=1575200828760922
Sun 2019-12-01 11:47:08.761011 UTC [s=9f7f37ae9a514254b88d1915cf7c59df;i=c3013b;b=9b747d2c918947f89f6e0ecabb670088;m=70ef8f356b;t=598a305d92694;x=ed748d99141d0386]
    PRIORITY=6
    _UID=0
    _GID=0
    _CAP_EFFECTIVE=3fffffffff
    _BOOT_ID=9b747d2c918947f89f6e0ecabb670088
    _MACHINE_ID=ec2ab651a12df8fa10696b87f7f042fb
    _HOSTNAME=relay-ap-northeast-1-2
    SYSLOG_FACILITY=3
    SYSLOG_IDENTIFIER=systemd
    _TRANSPORT=journal
    _PID=1
    _COMM=systemd
    _EXE=/nix/store/h6c0sb2fn70h4n33c7d3znr5bzakrzn6-systemd-243/lib/systemd/systemd
    _CMDLINE=systemd
    _SYSTEMD_CGROUP=/init.scope
    _SYSTEMD_UNIT=init.scope
    _SYSTEMD_SLICE=-.slice
    UNIT=jormungandr.service
    CODE_FILE=src/core/unit.c
    CODE_LINE=2365
    CODE_FUNC=unit_log_resources
    MESSAGE_ID=ae8f7b866b0347b9af31fe1c80b127c0
    INVOCATION_ID=a48e0dbf27004794829ecf0838875174
    CPU_USAGE_NSEC=893152317
    MESSAGE=jormungandr.service: Consumed 893ms CPU time, received 1.3M IP traffic, sent 2.0M IP traffic.
    IP_METRIC_INGRESS_BYTES=1385382
    IP_METRIC_INGRESS_PACKETS=8885
    IP_METRIC_EGRESS_BYTES=2180082
    IP_METRIC_EGRESS_PACKETS=7129
    _SOURCE_REALTIME_TIMESTAMP=1575200828761011
Sun 2019-12-01 11:47:08.761868 UTC [s=9f7f37ae9a514254b88d1915cf7c59df;i=c3013c;b=9b747d2c918947f89f6e0ecabb670088;m=70ef8f35e3;t=598a305d9270c;x=5b34bb9464f3317d]
    _BOOT_ID=9b747d2c918947f89f6e0ecabb670088
    _MACHINE_ID=ec2ab651a12df8fa10696b87f7f042fb
    _HOSTNAME=relay-ap-northeast-1-2
    _TRANSPORT=kernel
    PRIORITY=5
    SYSLOG_FACILITY=0
    SYSLOG_IDENTIFIER=kernel
    _SOURCE_MONOTONIC_TIMESTAMP=485071578877
    MESSAGE=audit: type=1130 audit(1575200828.760:58): pid=1 uid=0 auid=4294967295 ses=4294967295 subj==unconfined msg='unit=jormungandr comm="systemd" exe="/nix/store/h6c0sb2fn70h4n33c7d3znr5bzakrzn6-systemd-243/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Sun 2019-12-01 11:47:08.761946 UTC [s=9f7f37ae9a514254b88d1915cf7c59df;i=c3013d;b=9b747d2c918947f89f6e0ecabb670088;m=70ef8f3630;t=598a305d9275a;x=77a37fc1d3b7ff20]
    _BOOT_ID=9b747d2c918947f89f6e0ecabb670088
    _MACHINE_ID=ec2ab651a12df8fa10696b87f7f042fb
    _HOSTNAME=relay-ap-northeast-1-2
    _TRANSPORT=kernel
    PRIORITY=5
    SYSLOG_FACILITY=0
    SYSLOG_IDENTIFIER=kernel
    _SOURCE_MONOTONIC_TIMESTAMP=485071578881
    MESSAGE=audit: type=1131 audit(1575200828.760:59): pid=1 uid=0 auid=4294967295 ses=4294967295 subj==unconfined msg='unit=jormungandr comm="systemd" exe="/nix/store/h6c0sb2fn70h4n33c7d3znr5bzakrzn6-systemd-243/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Sun 2019-12-01 11:47:08.762700 UTC [s=9f7f37ae9a514254b88d1915cf7c59df;i=c3013f;b=9b747d2c918947f89f6e0ecabb670088;m=70ef8f3c2c;t=598a305d92d56;x=5e1f5b0fdf20da10]
    PRIORITY=6
    _UID=0
    _GID=0
    _CAP_EFFECTIVE=3fffffffff
    _BOOT_ID=9b747d2c918947f89f6e0ecabb670088
    _MACHINE_ID=ec2ab651a12df8fa10696b87f7f042fb
    _HOSTNAME=relay-ap-northeast-1-2
    SYSLOG_FACILITY=3
    CODE_FILE=src/core/job.c
    SYSLOG_IDENTIFIER=systemd
    JOB_TYPE=start
    _TRANSPORT=journal
    _PID=1
    _COMM=systemd
    _EXE=/nix/store/h6c0sb2fn70h4n33c7d3znr5bzakrzn6-systemd-243/lib/systemd/systemd
    _CMDLINE=systemd
    _SYSTEMD_CGROUP=/init.scope
    _SYSTEMD_UNIT=init.scope
    _SYSTEMD_SLICE=-.slice
    CODE_LINE=931
    CODE_FUNC=job_log_done_status_message
    JOB_RESULT=done
    MESSAGE_ID=39f53479d3a045ac8e11786248231fbf
    UNIT=jormungandr.service
    MESSAGE=Started Jormungandr node service.
    JOB_ID=53726
    INVOCATION_ID=40eedac6658a452b8f62c914c9d4c330
    _SOURCE_REALTIME_TIMESTAMP=1575200828762700
Sun 2019-12-01 11:47:08.763909 UTC [s=9f7f37ae9a514254b88d1915cf7c59df;i=c30140;b=9b747d2c918947f89f6e0ecabb670088;m=70ef8f3ddc;t=598a305d92f05;x=f57e95adbc08405c]
    _BOOT_ID=9b747d2c918947f89f6e0ecabb670088
    _MACHINE_ID=ec2ab651a12df8fa10696b87f7f042fb
    _HOSTNAME=relay-ap-northeast-1-2
    _TRANSPORT=kernel
    PRIORITY=5
    SYSLOG_FACILITY=0
    SYSLOG_IDENTIFIER=kernel
    _SOURCE_MONOTONIC_TIMESTAMP=485071580382
    MESSAGE=audit: type=1130 audit(1575200828.761:60): pid=1 uid=0 auid=4294967295 ses=4294967295 subj==unconfined msg='unit=jormungandr comm="systemd" exe="/nix/store/h6c0sb2fn70h4n33c7d3znr5bzakrzn6-systemd-243/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Sun 2019-12-01 11:47:08.772489 UTC [s=88b500d1b0454e0997be9fd88e5439de;i=c30141;b=9b747d2c918947f89f6e0ecabb670088;m=70ef8f5f79;t=598a305d950a2;x=d788244e33226221]
    PRIORITY=5
    CODE_FUNCTION=
    SYSLOG_IDENTIFIER=jormungandr
    _TRANSPORT=journal
    _UID=10015
    _GID=10015
    _COMM=jormungandr
    _CAP_EFFECTIVE=0
    _SYSTEMD_CGROUP=/system.slice/jormungandr.service
    _SYSTEMD_UNIT=jormungandr.service
    _SYSTEMD_SLICE=system.slice
    _BOOT_ID=9b747d2c918947f89f6e0ecabb670088
    _MACHINE_ID=ec2ab651a12df8fa10696b87f7f042fb
    _HOSTNAME=relay-ap-northeast-1-2
    MESSAGE=Starting jormungandr 0.8.0-rc3 (, release, linux [x86_64]) - [rustc 1.38.0 (625451e37 2019-09-23)]
    CODE_FILE=jormungandr/src/main.rs
    CODE_LINE=435
    CODE_MODULE=jormungandr
    TASK=init
    _EXE=/nix/store/55q9d5cmh5h3ifrwn62kj96smpab2n7p-jormungandr-0.8.0-rc3/bin/jormungandr
    _CMDLINE=/nix/store/55q9d5cmh5h3ifrwn62kj96smpab2n7p-jormungandr-0.8.0-rc3/bin/jormungandr --genesis-block /nix/store/dlqhg5shym40d8arl5xgbw2bzfryvh23-block-0.bin --config /nix/store/cbhzl97m3a5k4d24lhqvq51n70wdhns6-config.yaml
    _PID=28304
    _SYSTEMD_INVOCATION_ID=40eedac6658a452b8f62c914c9d4c330
    _SOURCE_REALTIME_TIMESTAMP=1575200828772489
Sun 2019-12-01 11:47:08.772521 UTC [s=88b500d1b0454e0997be9fd88e5439de;i=c30142;b=9b747d2c918947f89f6e0ecabb670088;m=70ef8f61f1;t=598a305d9531a;x=64004ceb7959da01]
    CODE_FUNCTION=
    SYSLOG_IDENTIFIER=jormungandr
    _TRANSPORT=journal
    _UID=10015
    _GID=10015
    _COMM=jormungandr
    _CAP_EFFECTIVE=0
    _SYSTEMD_CGROUP=/system.slice/jormungandr.service
    _SYSTEMD_UNIT=jormungandr.service
    _SYSTEMD_SLICE=system.slice
    _BOOT_ID=9b747d2c918947f89f6e0ecabb670088
    _MACHINE_ID=ec2ab651a12df8fa10696b87f7f042fb
    _HOSTNAME=relay-ap-northeast-1-2
    TASK=init
    _EXE=/nix/store/55q9d5cmh5h3ifrwn62kj96smpab2n7p-jormungandr-0.8.0-rc3/bin/jormungandr
    _CMDLINE=/nix/store/55q9d5cmh5h3ifrwn62kj96smpab2n7p-jormungandr-0.8.0-rc3/bin/jormungandr --genesis-block /nix/store/dlqhg5shym40d8arl5xgbw2bzfryvh23-block-0.bin --config /nix/store/cbhzl97m3a5k4d24lhqvq51n70wdhns6-config.yaml
    PRIORITY=4
    MESSAGE=Node started without path to the stored secret keys (not a stake pool or a BFT leader)
    CODE_FILE=jormungandr/src/settings/start/mod.rs
    CODE_LINE=142
    CODE_MODULE=jormungandr::settings::start
    _PID=28304
    _SYSTEMD_INVOCATION_ID=40eedac6658a452b8f62c914c9d4c330
    _SOURCE_REALTIME_TIMESTAMP=1575200828772521
Sun 2019-12-01 11:47:08.773898 UTC [s=88b500d1b0454e0997be9fd88e5439de;i=c30143;b=9b747d2c918947f89f6e0ecabb670088;m=70ef8f6504;t=598a305d9562d;x=fd391c602e9fc352]
    PRIORITY=5
    CODE_FUNCTION=
    SYSLOG_IDENTIFIER=jormungandr
    _TRANSPORT=journal
    _UID=10015
    _GID=10015
    _COMM=jormungandr
    _CAP_EFFECTIVE=0
    _SYSTEMD_CGROUP=/system.slice/jormungandr.service
    _SYSTEMD_UNIT=jormungandr.service
    _SYSTEMD_SLICE=system.slice
    _BOOT_ID=9b747d2c918947f89f6e0ecabb670088
    _MACHINE_ID=ec2ab651a12df8fa10696b87f7f042fb
    _HOSTNAME=relay-ap-northeast-1-2
    TASK=init
    _EXE=/nix/store/55q9d5cmh5h3ifrwn62kj96smpab2n7p-jormungandr-0.8.0-rc3/bin/jormungandr
    _CMDLINE=/nix/store/55q9d5cmh5h3ifrwn62kj96smpab2n7p-jormungandr-0.8.0-rc3/bin/jormungandr --genesis-block /nix/store/dlqhg5shym40d8arl5xgbw2bzfryvh23-block-0.bin --config /nix/store/cbhzl97m3a5k4d24lhqvq51n70wdhns6-config.yaml
    MESSAGE=storing blockchain in '"/var/lib/jormungandr/blocks.sqlite"'
    CODE_FILE=jormungandr/src/start_up/mod.rs
    CODE_LINE=32
    CODE_MODULE=jormungandr::start_up
    _PID=28304
    _SYSTEMD_INVOCATION_ID=40eedac6658a452b8f62c914c9d4c330
    _SOURCE_REALTIME_TIMESTAMP=1575200828773898
Sun 2019-12-01 11:47:08.776936 UTC [s=88b500d1b0454e0997be9fd88e5439de;i=c30144;b=9b747d2c918947f89f6e0ecabb670088;m=70ef8f70c6;t=598a305d961ef;x=a0745fcb97ea6cd7]
    CODE_FUNCTION=
    SYSLOG_IDENTIFIER=jormungandr
    _TRANSPORT=journal
    _UID=10015
    _GID=10015
    _COMM=jormungandr
    _CAP_EFFECTIVE=0
    _SYSTEMD_CGROUP=/system.slice/jormungandr.service
    _SYSTEMD_UNIT=jormungandr.service
    _SYSTEMD_SLICE=system.slice
    _BOOT_ID=9b747d2c918947f89f6e0ecabb670088
    _MACHINE_ID=ec2ab651a12df8fa10696b87f7f042fb
    _HOSTNAME=relay-ap-northeast-1-2
    PRIORITY=6
    TASK=init
    _EXE=/nix/store/55q9d5cmh5h3ifrwn62kj96smpab2n7p-jormungandr-0.8.0-rc3/bin/jormungandr
    _CMDLINE=/nix/store/55q9d5cmh5h3ifrwn62kj96smpab2n7p-jormungandr-0.8.0-rc3/bin/jormungandr --genesis-block /nix/store/dlqhg5shym40d8arl5xgbw2bzfryvh23-block-0.bin --config /nix/store/cbhzl97m3a5k4d24lhqvq51n70wdhns6-config.yaml
    CODE_FILE=jormungandr/src/start_up/mod.rs
    CODE_MODULE=jormungandr::start_up
    MESSAGE=parsing block0 from file path `"/nix/store/dlqhg5shym40d8arl5xgbw2bzfryvh23-block-0.bin"'
    CODE_LINE=54
    _PID=28304
    _SYSTEMD_INVOCATION_ID=40eedac6658a452b8f62c914c9d4c330
    _SOURCE_REALTIME_TIMESTAMP=1575200828776936
Sun 2019-12-01 11:47:08.883178 UTC [s=88b500d1b0454e0997be9fd88e5439de;i=c30145;b=9b747d2c918947f89f6e0ecabb670088;m=70ef910fcf;t=598a305db00f7;x=459abddce856d4cb]
    PRIORITY=5
    CODE_FUNCTION=
    SYSLOG_IDENTIFIER=jormungandr
    _TRANSPORT=journal
    _UID=10015
    _GID=10015
    _COMM=jormungandr
    _CAP_EFFECTIVE=0
    _SYSTEMD_CGROUP=/system.slice/jormungandr.service
    _SYSTEMD_UNIT=jormungandr.service
    _SYSTEMD_SLICE=system.slice
    _BOOT_ID=9b747d2c918947f89f6e0ecabb670088
    _MACHINE_ID=ec2ab651a12df8fa10696b87f7f042fb
    _HOSTNAME=relay-ap-northeast-1-2
    _EXE=/nix/store/55q9d5cmh5h3ifrwn62kj96smpab2n7p-jormungandr-0.8.0-rc3/bin/jormungandr
    _CMDLINE=/nix/store/55q9d5cmh5h3ifrwn62kj96smpab2n7p-jormungandr-0.8.0-rc3/bin/jormungandr --genesis-block /nix/store/dlqhg5shym40d8arl5xgbw2bzfryvh23-block-0.bin --config /nix/store/cbhzl97m3a5k4d24lhqvq51n70wdhns6-config.yaml
    CODE_FILE=jormungandr/src/network/bootstrap.rs
    CODE_LINE=48
    CODE_MODULE=jormungandr::network::bootstrap
    TASK=bootstrap
    PEER_ADDR=3.124.132.123:3000
    _PID=28304
    _SYSTEMD_INVOCATION_ID=40eedac6658a452b8f62c914c9d4c330
    MESSAGE=connecting to bootstrap peer 3.124.132.123:3000
    _SOURCE_REALTIME_TIMESTAMP=1575200828883178
```

**Comment by hodlonaut** [comment]
Can confirm also happening here on latest git master as of 2 Dec (0.8 rc3 equivalent):

Dec 02 09:28:01.102 INFO connection to peer failed, reason: protocol handshake failed: unknown error, node_id: 07756d25a63da185f7822e37c508f893c6a690cb3bc6d61c, peer_addr: 78.11.162.144:8010, task: network
Dec 02 09:28:02.662 INFO service finished with error, task: client-query
Dec 02 09:28:02.662 INFO Shutting down node

Happened twice on two starts, on third start the node continued running okay.

**Comment by rinor** [comment]
@hodlonaut is this still relevant with the latest release? If not can we close this one please. Thank you.

**Comment by hodlonaut** [comment]
Fine to close, haven't seen this issue in a long long time.
