### ISSUE TITLE
Build fails on latest stable Rust 1.43.0

### ISSUE THREAD

**Issue by AndrewWestberg** [input-output-hk/jormungandr#2133]
**Describe the bug**
Jormungandr & Jcli do not compile successfully (latest master branch)

```
$ rustc --version
rustc 1.43.0 (4fb7144ed 2020-04-20)

$ RUSTFLAGS="-C target-cpu=sandybridge" cargo install --path jcli --force
  Installing jcli v0.8.19-nightly (/data/cardano/jormungandr/jcli)
    Updating crates.io index
   Compiling libc v0.2.69
...
...
   Compiling rustls-native-certs v0.3.0
   Compiling chain-addr v0.1.0 (/data/cardano/jormungandr/chain-deps/chain-addr)
error[E0277]: the trait bound `chain_crypto::key::KeyPair<chain_crypto::algorithms::ed25519::Ed25519>: quickcheck::arbitrary::Arbitrary` is not satisfied
  --> chain-deps/chain-addr/src/testing.rs:36:32
   |
36 |     let kp: KeyPair<Ed25519> = Arbitrary::arbitrary(g);
   |                                ^^^^^^^^^^^^^^^^^^^^ the trait `quickcheck::arbitrary::Arbitrary` is not implemented for `chain_crypto::key::KeyPair<chain_crypto::algorithms::ed25519::Ed25519>`
   |
   = note: required by `quickcheck::arbitrary::Arbitrary::arbitrary`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0277`.
error: could not compile `chain-addr`.

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: failed to compile `jcli v0.8.19-nightly (/data/cardano/jormungandr/jcli)`, intermediate artifacts can be found at `/data/cardano/jormungandr/target`

Caused by:
  build failed
```

**Mandatory Information**
1. `jcli --full-version` output;
N/A
2. `jormungandr --full-version` output;
N/A

**To Reproduce**
1. Try to build either jormungandr or jcli with rust 1.43.0

**Expected behavior**
Successful build

**Comment by kairosway** [comment]
Same issue:

error[E0063]: missing field `per_vote_certificate_fees` in initializer of `chain_impl_mockchain::fee::LinearFee`
  --> jormungandr-lib/src/interfaces/linear_fee.rs:21:66
   |
21 | #[serde(deny_unknown_fields, rename_all = "snake_case", remote = "LinearFee")]
   |                                                                  ^^^^^^^^^^^ missing `per_vote_certificate_fees`

**Comment by NicolasDP** [comment]
This has been fixed in: #2137

**Comment by NicolasDP** [comment]
thanks for reporting the issue <3

**Comment by kairosway** [comment]
Thanks Nicolas, Still seeing compile error even after the recent commit:

error[E0599]: no method named `to_unsigned_header` found for struct `chain_impl_mockchain::header::builder::HeaderBuilder<chain_impl_mockchain::header::builder::HeaderCommonDone>` in the current scope
  --> jormungandr-lib/src/interfaces/block0_configuration/mod.rs:92:18
   |
92 |                 .to_unsigned_header()
   |                  ^^^^^^^^^^^^^^^^^^ help: there is a method with a similar name: `into_unsigned_header`

error[E0063]: missing field `per_vote_certificate_fees` in initializer of `chain_impl_mockchain::fee::LinearFee`
  --> jormungandr-lib/src/interfaces/linear_fee.rs:21:66
   |
21 | #[serde(deny_unknown_fields, rename_all = "snake_case", remote = "LinearFee")]
   |                                                                  ^^^^^^^^^^^ missing `per_vote_certificate_fees`

error[E0308]: mismatched types
   --> jormungandr-lib/src/wallet/account.rs:115:13
    |
115 |             self.internal_counter(),
    |             ^^^^^^^^^^^^^^^^^^^^^^^
    |             |
    |             expected struct `chain_impl_mockchain::accounting::account::account_state::SpendingCounter`, found `&chain_impl_mockchain::accounting::account::account_state::SpendingCounter`
    |             help: consider dereferencing the borrow: `*self.internal_counter()`

**Comment by NicolasDP** [comment]
You are not on latest master. this has been fixed too. Make sure to use latest master and to update your submodule (`git submodule update`).
